version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.1
    - 3.7.0
    - 4.0.3
    - 4.1.2
    - 4.1.3
  - dependency-name: "@chakra-ui/theme-tools"
    versions:
    - 1.1.0
    - 1.1.1
    - 1.1.3
  - dependency-name: "@sanity/types"
    versions:
    - 2.7.1
  - dependency-name: next-sanity
    versions:
    - 0.1.11
  - dependency-name: "@sanity/cli"
    versions:
    - 2.7.1
  - dependency-name: next-google-fonts
    versions:
    - 2.0.0
  - dependency-name: xo
    versions:
    - 0.38.1
    - 0.38.2
  - dependency-name: vercel
    versions:
    - 21.3.1
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.3.2
    - 1.3.3
